"""
This type stub file was generated by pyright.
"""

import logging
from .decorator import cross_origin
from .extension import CORS
from .version import __version__
from logging import NullHandler

"""
    flask_cors
    ~~~~
    Flask-CORS is a simple extension to Flask allowing you to support cross
    origin resource sharing (CORS) using a simple decorator.

    :copyright: (c) 2016 by Cory Dolphin.
    :license: MIT, see LICENSE for more details.
"""
__all__ = ['CORS', 'cross_origin']
rootlogger = ...
if rootlogger.level == logging.NOTSET:
    ...
